### ISSUE TITLE
Port Ares scripts to a .pbo instead of template

### ISSUE THREAD

**Issue by Cuel** [fparma/fparma-coop-template#4]
- Can be used in other missions
- Smaller size for template

@Tinter , @Mallow234, @MoistBaguette do you have anything you want to add / suggestions

**Comment by ComfyPillow** [comment]
:+1:  Would you consider opening up a repo for it, so people could porentially contribute to it aswell?

**Comment by Cuel** [comment]
Yep

**Comment by WhiteFox08** [comment]
~it never happened rest in peaice~

**Comment by Cuel** [comment]
it will

**Comment by Tinter** [comment]
I'm not familiar with Ares, so I don't know.

**Comment by Cuel** [comment]
Making a new repo for this.

**Comment by Cuel** [comment]
https://github.com/fparma/fparma-mods
