### ISSUE TITLE
Logging the new map drawing.

### ISSUE THREAD

**Issue by WhiteFox08** [fparma/fparma-coop-template#5]
Prevent spam during map loading.

**Comment by Tinter** [comment]
Not necessary.

**Comment by Tinter** [comment]
I could swear they were supposed to show the names next to the lines.

**Comment by Cuel** [comment]
It can be turned off with

``` sqf
findDisplay 12 displayCtrl 51 ctrlAddEventHandler ["KeyDown", {_this select 1 == 29}];
```

Taken from KK's twitter. 29 being L CTRL

So it should be possible to figure out when a line was placed aswell, for logging
In ACE, you could only place line markers if you had ACE_MapTools. Should we make it so here aswell?

**Comment by Cuel** [comment]
Seems to be ways around the above

> ENGINE
> Added: Authors of markers / drawn lines can now be displayed

This was in devbranch on the 25th, 1.60 was released 31st. I'm guessing it didn't make it in

**Comment by Tinter** [comment]
That explains it, I knew I read that somewhere.
I'd probably just wait until ACE fixes up something. It's not like people really spam the map with drawings, it's worse when they delete them and fuck up the briefing.

**Comment by Cuel** [comment]
I'm not sure ACE is doing much regarding the line drawing. They've deleted their own implementation and I haven't seen anything related to doing something with BI drawing

**Comment by Tinter** [comment]
I forget, is it in yet?

**Comment by Cuel** [comment]
Wait for next CBA, it has an eventhandler for created markers

**Comment by Cuel** [comment]
Actually I can add it while we wait for it

**Comment by Tinter** [comment]
20:39 - Cuel   ☂: lines have name of player who put it there now
20:40 - Cuel   ☂: im adding for normal markers
Ok it stays open.

**Comment by Tinter** [comment]
20:42 - Cuel   ☂: oh wait
20:42 - Cuel   ☂: it shows for normal markers aswell
20:42 - Cuel   ☂: welp
YOU'RE GONNA BURN ALRIGHT.
